baseURL: "https://mnrowe.com/"
title: Matthew N. Rowe
paginate: 20
theme: PaperMod

enableRobotsTXT: false
buildDrafts: false
buildFuture: true
buildExpired: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

params:
  #env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Matthew Rowe - Blog
  description: "Writing about the things I learn in my Cloud Native work: Kubernetes, Azure, Vim, Linux, Coding, Productivity"
  keywords:
    [
      Blog,
      Portfolio,
      CV,
      DevOps,
      Zettelkasten,
      Second Brain,
      Linux,
      Azure,
      Productivity,
      vim,
      neovim,
      unix,
    ]
  author: Matthew Rowe
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: A place for learning
    buttons:
      - name: Blog
        url: archives
      - name: Tags
        url: tags

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: About
      name: "About"
      url: /aboutme/
      weight: 10
    - identifier: Services
      name: "Services"
      url: /services/
      weight: 13
    - identifier: Courses
      name: "Courses"
      url: /courses/
      weight: 15
    - identifier: Contact
      name: "Contact"
      url: /contact/
      weight: 17
    # - identifier: Current
    #   name: "Current"
    #   url: /current/
    #   weight: 15
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: "Index"
      name: "Index"
      url: /archives/
      weight: 30
    # - identifier: "Articles"
    #   name: "Articles"
    #   url: /tags/article/
    #   weight: 40
    - identifier: Search
      name: 🔍
      url: /search/
      weight: 50


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

